### ISSUE TITLE
Is this software only suitable for whole genome sequencing data? what about whole 

### ISSUE THREAD

**Issue by stroke1989** [reimandlab/ActiveDriverWGSR#12]
Is this software only suitable for whole genome sequencing data? what about whole exome sequencing data?

**Comment by reimand0** [comment]
Hi - this software is only for WGS data since it uses adjacent genomic
regions to evaluate the background mutation rate of a genomic element. If
exome sequencing data were to be used, then the background mutation rate
would be underestimated and cause inflation of p-values and false
positives.
best,
Jüri
